name: IClinic Backend Production CI

on:
  pull_request:
    branches:
      - main


jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Copying configurations
        run: |
          cp contrib/env-sample .env

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv sync --dev

      #      - name: Check Syntax
      #        run: |
      #          pipenv run pycodestyle --statistics .
      - name: Run Migrations
        run: |
          pipenv run python manage.py migrate
      - name: Run Test
        run: |
          pipenv run python manage.py test

      - name: Test with pytest
        run: |
          pipenv run pytest . --cov=.

      - name: Posting Coverage
        env:
          CODECOV_TOKEN: "402274fc-7731-4cec-ab0a-9e80d55fadba"
        run: |
          pipenv run codecov

      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_NAME_PROD}}
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}

      - name: Auto-Merge Pull Request
        uses: reitermarkus/automerge@v1.5.2
