name: IClinic Backend Staging CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']


    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - name: Copying configurations
        run: |
          cp contrib/env-sample .env


      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv sync --dev

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test


      - name: Test with pytest
        run: |
          pipenv run pytest . --cov=.


      - name: Posting Coverage
        env:
          CODECOV_TOKEN: "402274fc-7731-4cec-ab0a-9e80d55fadba"
        run: |
          pipenv run codecov

      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_NAME_STAG}}
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
          method: squash